### ISSUE TITLE
[java] Breaking Java Grammar changes for PMD 7.0.0

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1019]
The goal is, to resemble the official Java Language Specification with PMD's own java grammar.
This makes it easier to maintain the grammar in the future and avoids special solution inside PMD.

#### Scheduled

*   [ ] Deal with ExplicitReceiverParameters explicitely in the grammar, see [JLS §8.4.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.1-220). Refs #1017 
*   [x] Add node for anonymous class declarations, refs #905 
*   [ ] Separate FormalParameter from `catch` clause formal parameters (see [JLS §14.20](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-CatchFormalParameter)) and other improvements around FormalParameter, refs #998
*   [ ] Improvements to LocalVariableDeclaration and FieldDeclaration, refs #1128 
*   [x] For ShiftExpression, it makes no sense to have these extra
RUNSIGNEDSHIFT and RSIGNEDSHIFT, which only match the token anyway. They could
set the image on their parent, but shouldn't be pushed on the stack... we can
use a #void production for that, like in oowekyala/pmd@87f05fc 
*  [ ] Remove setters from AccessNode interface and make FormalParameter, Resource and LocalVariableDeclaration not implement it anymore, refs #1307 
*   [x]  Parsing ASTClassOrInterfaceType recursively to preserve annotation and type parameter location, refs #1150. (Left recursive parsing is forbidden by javacc but we can build a "left-recursive node" by manipulating the jjtree stack
*  [ ] Make ImportDeclaration and FieldDeclaration regular nodes instead of TypeNodes
*  [x] Make ASTType and ASTReferenceType interfaces, make new node ArrayType -> helps type resolution, easier to specialize the API  
*  [ ] Use an ArrayDimensions node to represent array dimensions on ArrayType, VariableDeclaratorId, MethodDeclarator and other contexts instead of Dimensionable

#### Proposed

*  [ ] Split ForStatement into ForStatement and ForeachStatement 
*  [x] Make ASTLiteral an interface, use a different node for each type of literal (integer,    
*  [x] Merge UnaryExpression and UnaryExpressionNotPlusMinus. The two *productions* are needed for correct parsing, but there's no need to have two different *nodes*, especially since they have the same precedence. 
* [x] Add a VariableDeclaratorId under enum constant declaration. This would consistently make VariableDeclaratorId represent a declaration of any value (field, parameter, local var, enum constant, etc).
* [x] Clarify parsing of PrimaryPrefix/Suffix when using "this" or "super". See also https://github.com/pmd/pmd/pull/1530#discussion_r243271794

**Comment by jsotuyod** [comment]
@oowekyala should we merge #905 into this?

**Comment by oowekyala** [comment]
@jsotuyod I think adding that issue to the checklist is a good idea, but I'd prefer the issue to stay open. It gives room for clearer discussions/ easier referencing. Same for #998. I'll do that

I'd really love the grammar for expressions to be revamped for 7.0.0 too (#497), but I get a feeling this would have been a task for a GSoC given the number of rules and other clients to update. It also interacts with possible typeres GSoCs so it's hard to implement before the end of the summer

**Comment by adangel** [comment]
I'm closing this - the tasks are collected on https://github.com/pmd/pmd/wiki/PMD-7.0.0-Java
