### ISSUE TITLE
[doc] Documentations improvements tracker

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1139]
*   [x] General
    -   [x] #1769
    -   [x] #2417
    -   [x] #2795
*   [x] Layout / Styling
    -   [x] #2502 (in PMD 6.43.0 already, via #3804)
    -   [x] #2504 (in PMD 6.44.0 already, via #3811)
    -   [x] #2505 (in PMD 6.45.0 already, via #3883)
*   [x] Content
    *   User Documentation
        -   [x] #2267 (done in 6.22.0, XPath: Functions and Versions)
        -   [x] #2283 (done in 6.22.0, Add gradle docu)
        -   [x] #597
        -   [x] #2514

### Probably for PMD 7
* User Documentation
  * #2511
  * #4294

### Postponed for 7.x
* Layout, Styling
  * #2503
* General Content
  * #2506
  * #4292
  * #4293
* User Documentation
  * #893
  * #2507
  * #2508
  * #2509
  * #2510
  * #2512
  * #2513
* Developer Documentation
  * #2492
  * #2433
  * #2515
  * #2516
  * #2517
  * #906
* Rule Reference
  * #4295
  * #4296
  * #4297
  * #4298
  * #4299

**Comment by adangel** [comment]
Closing this tracking issue as done. The remaining tasks are either tracked by #3898 or are postponed.
