### ISSUE TITLE
[core] First steps to simplify the properties API

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1415]
#### Review of unused property types

Some property types are unused or barely used:
* MethodProperty -> can be removed altogether
* TypeProperty -> I can see how having a property for types is useful, but the property descriptors have no access to the aux classpath for now, which means the conversion will fail more often than not. I think, we can drop it, maybe replace it with a QualifiedNameProperty specific to Java in the future (qualified names don't need the auxclasspath). 
* FileProperty -> used only in the following:
https://github.com/pmd/pmd/blob/84d1519839a580cd411a635e18b3bce5708f2c86/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidDuplicateLiteralsRule.java#L52-L53

  The use case is definitely erroneous and a StringMultiProperty should be used instead. It can be removed I think
* FloatProperty -> never used, can be superseded by DoubleProperty
* LongProperty is never used either, but I can't see a strong reason to drop it. It may be useful in the future.

#### New validation scheme

Validating the properties could be done in the property descriptor. With Java 8, we could add the following method `addValidator(Predicate<T> pred)` to the builders class, which would allow java rules to register a validator. If a value doesn't pass the tests, then the rule is reported as dysfunctional and not run. This would be very flexible, although it doesn't allow XPath rules to validate their value. We could add some common validators to the XPath syntax in a later stage.

With this is place, we can simply drop support for the custom package restrictions of PackagedProperty and the min/max of NumericProperty, which seemed to be getting in the way too often. 

Since we're dropping these, we can also drop PropertyDescriptorField altogether. The schema only ever allowed the min and max attributes anyway.

#### Reunifying the multivalue and univalue properties

I think with a simple alteration of the ruleset schema we could drop the need for registering a delimiter, which means there need not be this big class hierarchy divide between multi- and single-value property descriptors (which would also reduce the number concrete property classes significantly). I'll describe that later. 

#### TODO

I'm scheduling the deprecations for the next release. The actual API changes are good for 7.0.0.

- [ ] Deprecate all property constructors. This avoids users relying on the implementation of the constructors and allows us to make more changes. The only way to build properties would be through the builders.
- [x] Deprecate NumericPropertyDescriptor and PackagedPropertyDescriptor. Once they're removed, the size of the class hierarchy and the amount of code duplication in the implementation can be significantly reduced. 
- [x] Deprecate PropertyDescriptorField
- [x] Deprecate FloatProperty, MethodProperty, FileProperty, TypeProperty and their PropertyTypeIds

**Comment by oowekyala** [comment]
#### Using generic property types instead of 30 non-generic classes

Going further, if we hide all property concrete classes, we may implement the whole framework with only a couple of generic concrete classes. This would require all code everywhere to use the interface PropertyDescriptor instead of the concrete classes. The builders would not be accessed through a static method on the property type, e.g. `IntProperty.named("foo")`, but through a common utility class providing builders for common properties. E.g. we'd get a builder with `PropertyFactory.intProperty("foo")`, and the `build` method would return a `PropertyDescriptor<Integer>` instead of an `IntProperty`. 

Using 2-3 classes total for the implementation compared to two classes for each property type would be a game changer for the future evolution of the framework. It would remove all the current duplicate boilerplate without losing flexibility. This would also make defining new types of descriptors extremely straightforward, probably just one call to a generic method. If you agree I think we can add this to the TODO:

- [ ] Create the PropertyFactory and the new generic classes/builders. This could be done in Java 7, keeping in mind it will in the end be a Java 8 API
- [ ] Deprecate all the concrete classes until 7.0.0. 
- [ ] Replace internal usages of constructors/ current builders by usage of PropertyFactory, all references to concrete classes with a reference to the interface

#### Removing isDefinedExternally

This method adds another layer of inconvenient boilerplate to the whole framework.

https://github.com/pmd/pmd/blob/65955881111e76de139054ad5220b92321e5a854/pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyDescriptor.java#L159

I added it because the RulesetWriter needs to know when a property is defined in the XML, and when it is just overridden. But it only makes sense to define a property in the XML if we're defining an XPath rule. Properties defined on other rules and on rule references can't be used and it should be impossible to define a property there. We should try to forbid it when changing the ruleset schema. In the meantime, I think we can use that assumption to get rid of isDefinedExternally, and drop support for it.

**Comment by oowekyala** [comment]
Closed in favour of #1432 and related wiki page
