### ISSUE TITLE
[core] Implementation plan for property framework changes

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1432]
This issue serves as easy reference for PRs, and as a discussion for the changes described [on the wiki](https://github.com/pmd/pmd/wiki/Property-framework-7-0-0). Replaces #1415 

## Implementation plan

<details>
  <summary>Due on 6.10.0 :heavy_check_mark: done</summary>
  <p>

- [x] **(#1420)** Deprecate all classes and methods to be removed
- [x] **(#1470)** Introduce a PropertyFactory, a PropertyConstraint, etc to get a property creation API
  that is as capable as the current framework, and source compatible with the 7.0.0 API. 
  * This doesn't need to implement anything about PropertyXmlSyntax, and doesn't entail changes to the PropertyDescriptor interface. It could be integrated to the current property framework seamlessly
- [x] Deprecate all concrete property types, migrate internal usages to use PropertyFactory
  (should allow us to spot some bugs, enrich API, etc):
    - [x] #1420
      - [x] MethodMultiProperty
      - [x] MethodProperty
      - [x] TypeMultiProperty
      - [x] TypeProperty
      - [x] FileProperty
    - [x] #1485 IntegerProperty
    - [x] #1486 
      - [x] DoubleProperty
      - [x] DoubleMultiProperty
      - [x] FloatMultiProperty
      - [x] FloatProperty
      - [x] IntegerMultiProperty
    - [x] #1487 RegexProperty
    - [x] #1501
      - [x] StringMultiProperty
      - [x] StringProperty
    - [x] #1502 
      - [x] BooleanMultiProperty
      - [x] BooleanProperty
    - [x] #1505 
      - [x] EnumeratedMultiProperty
      - [x] EnumeratedProperty
    - [x] #1506  
      - [x] CharacterMultiProperty
      - [x] CharacterProperty
      - [x] LongMultiProperty
      - [x] LongProperty

</p>
</details>

Due on 7.0.0

- [x] **Removing StatisticalRule** is a prerequisite, because its properties can not be converted to the framework
  - [x] #1750
  - [x] #1772
  - [x] #2005
- [x] #2450

### Probably for PMD 7
* #4301
* #4303

### Postponed
* #4302
* #4304
* #4305
* #4306
* #3869 
* #1204

**Comment by adangel** [comment]
Closing this tracking issue as done. The remaining tasks are either tracked by #3898 or are postponed.
