### ISSUE TITLE
[core] Merging Javacc build scripts

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2239]
#### TODO on master

- [x]  #2244 Internalize CharStream and its implementations 
- [x]  #2244 Internalize all classes generated by JavaCC (in particular, `*ParserConstants`, `*ParserTreeConstants`, `*ParserTokenManager`).

#### TODO on 7.0

- PMD languages to port
   - [x] Java, Modelica #2211 
   - [x] VM #2289 
   - [x] VF, JSP #2294
   - [x] PLSQL #2369 
- CPD languages to port (must set the property `no-jjtree` on the target in the pom.xml) 
   - [x] Python #2293 
   - [x] ObjectiveC #2361 
   - [x] Javascript #2362 
   - [x] Matlab #2359 
   - [x] C++ #2360 
- TODO once all languages are ported:
   - [x] Move CharStream to `impl.javacc` package
   - [x] #4065
   - [x] Cleanup TokenMgrError
      - [x] Remove "error codes" 
      - [ ] maybe rename to something not javacc specific (eg LexException/ScanException)
         - [ ] LexException, then Tokenizer -> CpdLexer	
   - [x] Cleanup AbstractNode (#2447)
       - [x] Remove token methods & fields and put them on AbstractJjtreeNode
       - [x] Remove text position fields (beginLine/etc)
       - [x] Remove ID field
   - [x] Cleanup Node interface (#2447)
       - [x] Remove JJTree methods (jjtClose, jjtGetId, etc)
   - [x] Decide on `*TokenKinds`: ~published API~ or internal?
   - [x] Decide on `*TokenManager`: ~published API~ or internal?

Should we really consider `*TokenKinds` a published API? Since token kinds are compile-time constants, adding or removing tokens in the grammar may break binary compatibility implicitly.

**Comment by oowekyala** [comment]
Note: on master the visitor interfaces generated by Javacc are deprecated, but shouldn't be (eg [JavaParserVisitor](https://javadoc.io/doc/net.sourceforge.pmd/pmd-java/latest/net/sourceforge/pmd/lang/java/ast/JavaParserVisitor.html))

**Comment by adangel** [comment]
I'll try to port PLSQL now....

**Comment by oowekyala** [comment]
I think this can is done now. The only remaining thing is #4065
