### ISSUE TITLE
[core] XPath Improvements for PMD 7

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2523]
- [x] #1825
- [x] #1938
- [x] #2872 (fixed on PMD6 already)
- [x] #1687
- [x] #2451 (fixed on PMD6 already)
- [x] #2614
- [x] #1939 (fixed on PMD6 already)
- [x] #915 (won't fix)
  - [x] fixed on PMD6 via #3864 
- [x] #1244 (won't fix)
- [x] #1243 (won't fix)
- [x] #3207
* Optional improvements ("nice to have")
  - [x] #1171 (won't fix)
  - [x] #2917

### Probably for PMD 7
* #4308
* #4309

### Postponed
* #1676
* #1170
* #2217
* #1787

**Comment by adangel** [comment]
Closing this tracking issue as done. The remaining tasks are either tracked by #3898 or are postponed.
