### ISSUE TITLE
[doc] Differences in rules in pmd 7 vs pmd 6

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3123]
This document describes minor differences in the behavior of certain rules in PMD 7. Some of those items may be considered bugs that need to be fixed in pmd 7. Others are just reported here for documentation

- [x] [AvoidReassigningLoopVariables](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#avoidreassigningloopvariables):
  - The rule might not report anymore all reassignment of the control variable in for-loops, see the test case.
  - https://github.com/pmd/pmd/pull/3113#discussion_r579205794
  - This test case is deactivated and was working before with PMD 6.x. It will only detect now the last two assignments (15,16) but not the two before (13,14): https://github.com/pmd/pmd/blob/9f13f12e4cd11661a10294441f68c7ab8b7d452c/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningLoopVariables.xml#L676-L704
  - Test case in PMD 6.55.0: https://github.com/pmd/pmd/blob/ef3455348603aa25f86894b9930f05f141f44d20/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningLoopVariables.xml#L580-L607

- [x] Reported line ranges - #4439

- [x] "ArrayIsStoredDirectly now reports on the assignment and not the formal parameter so line numbers will probably move." - #3127

- [x] For the statistical rules (like NcssCount, ExcessivePackageBodyLineCount, ...)
        the parameter "minimum" is now an integer and not a decimal anymore.
        See [[core] Remove statistical rule (final step) #2005](https://github.com/pmd/pmd/pull/2005),
        [[java] Remove java statistical rules #1772](https://github.com/pmd/pmd/pull/1772),
        [[apex] Remove apex statistical rules #1750](https://github.com/pmd/pmd/pull/1750).
  - Removed properties `topscore` and `sigma` for the following rules:
    - Apex: ExcessiveClassLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_apex_design.html#excessiveclasslength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#excessiveclasslength)
    - Apex: ExcessiveParameterList [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_apex_design.html#excessiveparameterlist) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#excessiveparameterlist)
    - Apex: ExcessivePublicCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_apex_design.html#excessivepubliccount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#excessivepubliccount)
    - Apex: NcssConstructorCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_apex_design.html#ncssconstructorcount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#ncssconstructorcount)
    - Apex: NcssMethodCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_apex_design.html#ncssmethodcount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#ncssmethodcount)
    - Apex: NcssTypeCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_apex_design.html#ncsstypecount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#ncsstypecount)
    - Java: Rules, that are anyway deprecated: ExcessiveClassLength, ExcessiveMethodLength, NcssConstructorCount, NcssMethodCount, NcssTypeCount
    - Java: ExcessiveImports [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_design.html#excessiveimports) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#excessiveimports)
    - Java: ExcessiveParameterList [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_design.html#excessiveparameterlist) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#excessiveparameterlist)
    - Java: ExcessivePublicCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_design.html#excessivepubliccount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#excessivepubliccount)
    - Java: SwitchDensity [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_design.html#switchdensity) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#switchdensity)
      - :warning: inconsistency: minimum is still a double, not an int here
      - while we calculate the ratio between number of statements and number of labels, we shouldn't pretend that this is an exact rule - it's anyway a best guess, that high switch density is a problem. I don't think, it makes a big difference between 10.2 and 10. You e.g. want to report, when the density is bigger than 10 or bigger then 5. We don't need to report level accuracy here.
    - PLSQL: ExcessiveMethodLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#excessivemethodlength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#excessivemethodlength)
    - PLSQL: ExcessiveObjectLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#excessiveobjectlength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#excessiveobjectlength)
    - PLSQL: ExcessivePackageBodyLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#excessivepackagebodylength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#excessivepackagebodylength)
    - PLSQL: ExcessivePackageSpecificationLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#excessivepackagespecificationlength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#excessivepackagespecificationlength)
    - PLSQL: ExcessiveParameterList [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#excessiveparameterlist) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#excessiveparameterlist)
    - PLSQL: ExcessiveTypeLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#excessivetypelength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#excessivetypelength)
    - PLSQL: NcssMethodCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#ncssmethodcount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#ncssmethodcount)
    - PLSQL: NcssObjectCount [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#ncssobjectcount) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#ncssobjectcount)
    - PLSQL: NPathComplexity [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_plsql_design.html#npathcomplexity) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_plsql_design.html#npathcomplexity)
    - VM: ExcessiveTemplateLength [6.55.0](https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_vm_design.html#excessivetemplatelength) [7.0.0-rc1](https://docs.pmd-code.org/latest/pmd_rules_vm_design.html#excessivetemplatelength)

- [x] violationSuppressXPath now requires XPath 2.0 or 3.1 - in PMD6 it was XPath 1.0. This is a breaking change. See also #1676.

- [x] Changed/removed properties for rules - already documented in the release notes, but incomplete
  - Java: NPathComplexity: property `minimum` removed (was deprecated with 6.0.0 already)
  - Apex: code climate properties removed - see #1648. Properties: `cc_categories`, `cc_remediation_points_multiplier`, `cc_block_highlighting`
    - many rules
  - Java: MethodNamingConventions: property `checkNativeMethods` removed (deprecated since 6.3.0)
  - Java: CyclomaticComplexity: property `reportLevel` removed (deprecated since 6.0.0)
  - Java: ImmutableField: property `ignoredAnnotations`, see #4489 
  - Java: AvoidDuplicateLiterals: property `exceptionfile` removed (deprecated since 6.10.0)

- [x] Other disabled test cases in PMD 7, that were enabled before in PMD 6.x
  - [PreserveStackTrace](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#preservestacktrace): 3 test cases disabled, but these test cases are new for PMD 7.
  - [UnusedAssignment](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#unusedassignment): 1 test case disabled. New test case only present in PMD 7.
  - [UnusedPrivateMethod](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod): 2 test cases disabled. Both are disabled in PMD 6 as well.
  - [UseVarArgs](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#usevarargs): 1 test case disabled. Disabled in PMD 6 as well.
  - [MethodNamingConventions](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#methodnamingconventions): 1 test case disabled. Disabled in PMD 6 as well.
  - [UnnecessaryFullyQualifiedName](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname): 1 test case disabled. New test case only present in PMD 7.
  - [UnnecessaryImport](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryimport): 1 test case disabled.
    - "Used static import" - will produce a false positive with incomplete auxclasspath: https://github.com/pmd/pmd/blob/5eee9f6a13b0c6d29c723cb7c373461516293bae/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryImport.xml#L161-L173
  - [UnnecessaryReturn](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryreturn): 1 test case disabled. New test case only present in PMD 7.
  - [InvalidLogMessageFormat](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#invalidlogmessageformat): 1 test case disabled. Disabled in PMD 6 as well
  - :heavy_check_mark: Conclusion - nothing to do here. No special differences visible.

- [x] Check diff regression report:
  - https://chunk.io/pmd/9ba3a41020364534a828c66631585431/diff/index.html
  - Created with the following command: `bundle exec pmdtester --local-git-repo ../pmd --base-branch pmd_releases/6.55.0 --patch-branch master --config ../pmd/.ci/files/all-regression-rules.xml --list-of-project ../pmd/.ci/files/project-list.xml --mode online --error-recovery --baseline-download-url https://pmd-code.org/pmd-regression-tester/`
  - Apex: [ExcessivePublicCount](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#excessivepubliccount): in PMD 6, it reported it per file. Now it is reported per class. This makes a difference when inner classes are used. That is actually a implicit bug fix done with PMD 7 - see https://chunk.io/pmd/9ba3a41020364534a828c66631585431/diff/fflib-apex-common/index.html#section-violations . E.g. [fflib_Application.cls](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/7e0891efb86d23de62811af56d87d0959082a322/sfdx-source/apex-common/main/classes/fflib_Application.cls)
    - see #4497
    - #4509 
  - Java: [LocalVariableCouldBeFinal](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#localvariablecouldbefinal) - seems to have now fixed a false positive (kind of) for lambdas but also introduced a false negative for local variables declared with "var". But not only for var. See https://chunk.io/pmd/9ba3a41020364534a828c66631585431/diff/java-regression-tests/index.html#section-violations
    - It's actually now, that we don't report unused variables anymore. The removed violations are all unused vars.
    - #4511
  - Java: [MethodArgumentCouldBeFinal](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#methodargumentcouldbefinal) - false negative. Maybe only for varargs or array arguments. No, also for int params. Maybe we just don't report unused params anymore? see https://chunk.io/pmd/9ba3a41020364534a828c66631585431/diff/java-regression-tests/index.html#section-violations
    - Yes, unused params are not reported anymore.
    - #4512
  - Java: [ShortVariable](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#shortvariable) seems to find now also short enum constant names. Maybe update rule doc?
    - Yes, that's due to the grammar change: The enum constant now produces also a VariableDeclarationId node.
  - Java: [CommentSize](https://docs.pmd-code.org/latest/pmd_rules_java_documentation.html#commentsize) doesn't count the leading comment markers like `// ` or `/*` or ` *` anymore... seems like. TODO, verify.
    - Yes, that's the case: see #4369 
  - Java: [ImplicitySwitchFallthrough](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#implicitswitchfallthrough) - now reports on the case statements rather than on the switch statement. This results in more violations (maybe multiple per switch). But it is more accurate that way.
  - Java: [ClassWithOnlyPrivateConstructorsShouldBeFinal](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#classwithonlyprivateconstructorsshouldbefinal)
    - :heavy_check_mark: now finds inner classes reliably. This is due to fix #2536 probably
  - Java: [PrematureDeclaration](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#prematuredeclaration)
    - :heavy_check_mark: Doesn't report unused variables anymore, see #3221 
  - Java: [UselessOperationOnImmutable](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#uselessoperationonimmutable)
    - finds more cases now. But on first glance, they are all legit.
    - #4513
  - Java: [AvoidLiteralsInIfCondition](https://docs.pmd-code.org/latest/pmd_rules_java_errorprone.html#avoidliteralsinifcondition)
    - possible false negative when a nested condition is used, e.g. https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/main/java/com/puppycrawl/tools/checkstyle/checks/design/ThrowsCountCheck.java#L285 is not detected anymore
    - behavior of the rule depends on the property `ignoreExpressions` which is by default true: So we have actually one fix for false positives (expressions are correctly now ignored) and one fix for false negatives for String literals, which weren't reported before PMD 7.
    - #4514
  - Java: [CommentRequired](https://docs.pmd-code.org/latest/pmd_rules_java_documentation.html#commentrequired) seems to have changed a lot. Many new violations but also many removed. see https://chunk.io/pmd/9ba3a41020364534a828c66631585431/diff/checkstyle/index.html#section-violations
    - Some difference in behavior: for class comments, when the class is annotated, then the class comment must be before the annotation. e.g. https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/it/resources/com/google/checkstyle/test/chapter7javadoc/rule734nonrequiredjavadoc/InputInvalidJavadocPosition.java#L48 is now correctly detected to have no javadoc. Actually, that's "just" a bugfix.
    - Annotations are considered. Maybe they weren't with PMD 6?
      - no they weren't. The node type changed from `AnnotationMethodDeclaration` to `MethodDeclaration` - now these are considered methods and are reported
      - But the annotation type itself is missing, as well as records.
      - Created for that: #4515
    - There are really some false negatives now: https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/it/resources/org/checkstyle/suppressionxpathfilter/noclone/SuppressionXpathRegressionNoCloneOne.java#L5
      - No, these are overridden methods. PMD now can detect overridden methods even without the `@Override` annotations. See #3757.
  - Java: [UnusedLocalVariable](https://docs.pmd-code.org/latest/pmd_rules_java_bestpractices.html#unusedlocalvariable)
    - :warning: seems to have a lot new false positives. E.g. `i` is said to be unused in https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/it/resources/com/google/checkstyle/test/chapter4formatting/rule451wheretobreak/InputMethodParamPad.java#L202 but it is read when assigning a new value to itself. Or do we ignore the expressions, if the left side also contains the variable? While this example is very contrived, I think, this is a false positive.
      - actually, these new cases are correct. Yes, compound assignment don't count as usage anymore, so all the new cases do something like `i++`, but otherwise don't use the vars.
      - See #4517
    - :heavy_check_mark: now also finds unused closeables in try-with-resources. While the closeable will be implicitly used to close it, I think it's good to highlight such cases, as it might be just unnecessary code. Example: https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/coding/fallthrough/InputFallThrough.java#L29
      - See #4516
    - Overall, we have 3 false negative fixed, which might lead to a lot of new violations when upgrading to PMD 7.
    - And one false positive: #4518
  - Java: [UnnecessaryImport](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryimport)
    - possible false positive: https://github.com/checkstyle/checkstyle/blob/checkstyle-9.1/src/test/java/com/puppycrawl/tools/checkstyle/AbstractXmlTestSupport.java#L22 - it's used in line 230. Did I have a wrong auxclasspath here? Hm... I had <local-repo>/com/google/truth/truth/1.1.3/truth-1.1.3.jar on the classpath though
    - This has already been reported here: #4432
