### ISSUE TITLE
[java] Support JDK 17 (LTS)

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#3366]
[OpenJDK 17](https://openjdk.java.net/projects/jdk/17/)  GA is scheduled for 2021/09/14.
So we should add support for that at the latest with PMD 6.38.0 (August 2021) or earlier.

The following JEPs are important for us:

* [JEP 406](https://openjdk.java.net/jeps/406): Pattern Matching for switch (Preview)
* [JEP 409](https://openjdk.java.net/jeps/409): Sealed Classes

In summary: https://javaalmanac.io/jdk/17/

This issue is similar to the previous: #3079 

EA Release of JDK17 is available here: http://jdk.java.net/17/

**Tasks:**

- [x] Add new java language versions 17 and 17-preview.
    - 17 is the new default
    - also update cli_reference.md
    - also add in KotlinTestingDsl.kt.
- [x] Update asm dependency:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor.ASM_API is necessary
- [x] Promote "Sealed Classes" (409) to a standard feature. Note, there might be some small changes from last preview. Removed experimental annotation
    - "This JEP proposes to finalize Sealed Classes in JDK 17, with no changes from JDK 16."
- [x] Implement "Pattern Matching for switch" (406) as a preview feature, mark AST classes as experimental, if needed.
    - https://openjdk.java.net/jeps/406
    - http://cr.openjdk.java.net/~gbierman/jep406/latest/
- [x] Remove java language version 15-preview
- [x] Write release notes
- [x] Prepare merge for PMD 7 -> #3414
