### ISSUE TITLE
[core] Text documents epic

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3784]
This is a task list for the series of PRs I mentioned in https://github.com/pmd/pmd/issues/693#issuecomment-995927263. These are for PMD 7

- [x] #3692 
  - [x] #3762 (merge this before)
- [x] #3893 
  - [x] #3785 (merge this before)
  - What:
    - Replace the current document API which is dead code
    - Introduce TextFile to replace DataSource
    - Revamp initial file collection phase (internals of the FileProcessor of #3785)
    - Introduce Chars, a string slice type. This allows us to share the char array of the source file, and not duplicate it when eg we parse a subfile in an embedded language. It also enables more efficient analysis of eg comments.
  - Why:
    - Bridge the gap between CPD's SourceCode and PMD's DataSource
    - Have a higher-level abstraction stack than DataSource (eg data source provides only byte streams, we want to work on character streams)
    - TextFile is both readable and writable, a prerequisite to #693 
    - FileLocation for #730
    - Avoid unnecessary string copies 
- [x] #4044  Revamp Javacc infrastructure
   - What:
     - Rewrite CharStream so as not to rely on javacc-generated sources in pmd-core
     - Build CharStream on top of TextDocuments as a first-class API
   - Why:
     - Control the support for JavaCC-generated languages entirely, without relying on javacc-generated sources
     - Exploit TextDocuments and Chars correctly, to avoid string copies
     - Finish #2239
     - Fix some problems in CPD tokenizers related to string escape
- [x] #4237 
   - What:
     - Stabilize how Comment nodes are represented
     - Use Chars properly in comments to avoid string copies in rules
   - Why:
     - A todo item leftover from the initial grammar revamp

### Remaining tasks

- #4325

**Comment by adangel** [comment]
I'm closing this as done. The remaining task (#4325) is tracked separately.
