### ISSUE TITLE
[java] Support JDK 18

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#3809]
[OpenJDK 18](https://openjdk.java.net/projects/jdk/18/)  GA is scheduled for 2022/03/22.
So we should add support for that with the next PMD version.

The following JEPs are important for us:
* [JEP 413](https://openjdk.java.net/jeps/413): Code Snippets in Java API Documentation
* [JEP 420](https://openjdk.java.net/jeps/420): Pattern Matching for switch (Second Preview)

In summary: https://javaalmanac.io/jdk/18/

This issue is similar to the previous: #3366

EA Release of JDK18 is available here: http://jdk.java.net/18/

**Tasks:**

- [x] Add new java language versions 18 and 18-preview.
    - 18 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
- [x] Update asm dependency:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor.ASM_API if necessary
    - :heavy_check_mark: we already use the latest version 9.2
- [x] Update implementation for "Pattern Matching for switch" (406, 420) as a preview feature, mark AST classes as experimental, if needed.
    - https://openjdk.java.net/jeps/406 (preview 1)
    - https://openjdk.java.net/jeps/420 (preview 2)
    - http://cr.openjdk.java.net/~gbierman/jep420/jep420-20211208/specs/patterns-switch-jls.html
- [x] Remove java language version 16-preview
    - update also java.md and ant.md
    - update KotlinTestingDsl.kt
- [x] Write release notes
- [x] Prepare merge for PMD 7 -> #3838
