### ISSUE TITLE
PMD 7 Tracking Issue

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3898]
# :heavy_check_mark: Release Candidate 1
**Topic:** Finish open PRs and finish Java module
**Version:** 7.0.0-rc1

<details>
<summary>Task list for 7.0.0-rc1</summary>

## Open PRs
* `in:cli`
  * [x] #4235
* `in:testing`
  * [x] #4155
* `in:pmd-internals`
  * [x] #4342
* unlabelled
  * [x] #4060

## Tasks, that are almost done
(because we have an open PR for it)
* `in:pmd-internals`
  * [x] #881
    * PR: #4342
* `in:testing`
  * [x] #3797
    * PR: #4155
* General Language Plugin Support
  * [x] #2518
    * PR: #4060
  * [x] #3782
    * PR: #4060

## Java
* `in:ast`
  * [x] #4317
* [x] #4367

## Other
* General Language Plugin Support
  * [x] #4120
  	* [x] #4387 
* `in:pmd-internals`
  * [x] #2873
* `in:testing`
  * [x] #2435
* [x] #4373
* [x] :exclamation: Check release scripts
  * Do the release scripts for pmd7 work on master? Doc deployment, etc.

</details>

# :heavy_check_mark: Release Candidate 2
**Topic:** Finish Documentation
**Version:** 7.0.0-rc2

<details>
<summary>Task list for 7.0.0-rc2</summary>

## ANTLR Support
  * [x] #2500
    * #4471
  * [x] #2501
    * #4473

## Documentation
* User Documentation
  * [x] #3123
    * #4501
  * [x] #4307
    * #4447
</details>

# :heavy_check_mark: Release Candidate 3

<details>
<summary>Task list for 7.0.0-rc3</summary>

Miscellaneous bug fixes - see release notes
</details>

# :heavy_check_mark: Release Candidate 4
**Topic:** Cleanup, Release Notes, Prepare dependent projects
**Version:** 7.0.0-rc4

<details>
<summary>Task list for 7.0.0-rc4</summary>

## Spill over from rc2

* User Documentation
  * [x] #4294
    * #4590 
* Developer Documentation
  * [x] #4303
    * [x] Part of #4380

## Spill over from rc3
* Cleanup Tasks (remove deprecated API, promote experimental api, DeprecatedUntil700)
  * Property API
    * [x] #4301
       * [x] Part of #4380
    * [x] #4302
       * [x] Part of #4380
* Apex
  * `in:grammar`
    * [x] #4479

## Dependents update

Some dependent projects need to be updated when we release PMD 7

* [x] [pmd/pmd.github.io](https://github.com/pmd/pmd.github.io)
  * Branch: `pmd7`
* [x] [pmd/pmd-designer](https://github.com/pmd/pmd-designer)
  * Branch: `compat-7.0` 
  * pmd/pmd-designer#43
* [x] [pmd/pmd-eclipse-plugin](https://github.com/pmd/pmd-eclipse-plugin)
  * pmd/pmd-eclipse-plugin#122
* [x] [pmd/pmd-examples](https://github.com/pmd/pmd-examples)
  * pmd/pmd-examples#3
* [x] https://github.com/ChuckJonas/vscode-apex-pmd/issues/124
  * https://github.com/ChuckJonas/vscode-apex-pmd/pull/130

</details>

# :heavy_check_mark: Final 7.0.0
**Topic:** Cleanup, Release Notes, Prepare dependent projects
**Version:** 7.0.0

<details>
<summary>Task list for Final 7.0.0</summary>

## Spill over from rc2

* Developer Documentation
  * [x] #995
    * #4756 
  * [x] #2511
    * #4762
  * [x] #3175
    * #4661
  * [x] #4308
    * #4764
  * [x] #4319
    * #4766

## Spill over from rc3
* Cleanup Tasks (remove deprecated API, promote experimental api, DeprecatedUntil700)
  * Java
    * [x] #1307
      * fixed by #4768
    * [x] #3751
      * fixed by #4768
  * `in:pmd-internals`
    * [x] #1027
       * [x] Partially covered in #4380 but XPath properties are still pending
       * [x] #4724 
  * `in:ruleset-xml`
    * [x] #4313
      * fixed by #4786
    * [x] #4314
      * fixed by #4795
  * `in:grammar`
    * [x] #4065
      * it's small
      * it can be considered as cleanup
      * fixed by #4797 
  * Property API
    * [x] #4312
      * fixed by #4798
  * Rule API
    * [x] #3917
      * fixed by #4799
  * Renderer and Reporting and Violation API
    * [x] #3903
      * fixed by #4803
  * `in:xpath`
    * [x] #4309
      * fixed by #4804
  * unlabelled
    * [x] #3905
      * fixed by #4808
    * [x] #4348
      * fixed by #4809
    * [x] #4349
      * fixed by #4811 
* Apex
  * `in:grammar`
    * [x] #3766
      * almost done
      * PMD7 wouldn't depend anymore on jorje (smaller footprint, etc.)
      * fixed by #4806

## Dependents update

Some dependent projects need to be updated when we release PMD 7

* :x: [apache/maven-pmd-plugin](https://github.com/apache/maven-pmd-plugin)
  * Branch: `pmd7`
  * https://github.com/pmd/pmd/discussions/4478
  * https://issues.apache.org/jira/browse/MPMD-379
  * Post-poned, since there is a solution now: https://docs.pmd-code.org/snapshot/pmd_userdocs_tools_maven.html#using-pmd-7-with-maven-pmd-plugin
* https://github.com/gradle/gradle/issues/24502
  * Tested it with gradle 8.6 - it works with PMD 7
  * The referenced issue is about updating the default version to PMD 7 :question: 
* [x] https://github.com/m2e-code-quality/m2e-code-quality/issues/327

</details>

# Tasks, that are postponed

See [Milestone 7.x](https://github.com/pmd/pmd/milestone/73)

# Finished

See [Milestone 7.0.0 - closed](https://github.com/pmd/pmd/milestone/19?closed=1)

**Comment by Devamparikh** [comment]
Hey there, I want help in migrating Junit4 to Junit5. Is there any open issue I can work on?

**Comment by stephen-carter-at-sf** [comment]
Hello everyone. On behalf of the Salesforce Code Analyzer team, I am reaching out to ask if there is an estimated date when PMD 7 will be released to be generally available and no longer a release candidate. Is it possible to give us an estimate on this?

**Comment by jsotuyod** [comment]
@stephen-carter-at-sf we are aiming to cut a release by the end of next week or the weekend at the latest. Only some upkeeping left and merging 2 open PRs with fixes based on RC feedback.

**Comment by adangel** [comment]
The target release date for PMD 7 will be March, 22nd 2024.

Closing this issue now, since all tasks have been done.
