### ISSUE TITLE
[java] Support JDK 19

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4015]
[OpenJDK 19](https://openjdk.java.net/projects/jdk/19/)  GA is scheduled for 2022/09/20.
So we should add support for that with PMD version 6.49.0 or earlier.

The following JEPs are important for us:
*   [JEP 405: Record Patterns (Preview)](https://openjdk.java.net/jeps/405)
    * destructuring of record components with instanceof
*   [JEP 427: Pattern Matching for switch (Third Preview)](https://openjdk.java.net/jeps/427)
    * new keyword `when`...

In summary: https://javaalmanac.io/jdk/19/

This issue is similar to the previous: #3809 

EA Release of JDK19 is available here: http://jdk.java.net/19/

**Tasks:**

- [ ] Add new java language versions 19 and 19-preview.
    - 19 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
- [ ] Update asm dependency:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor.ASM_API if necessary
- [ ] Update implementation for "Pattern Matching for switch" (406, 420, 427) as a preview feature, mark AST classes as experimental, if needed.
    - https://openjdk.java.net/jeps/406 (preview 1)
    - https://openjdk.java.net/jeps/420 (preview 2)
    - https://openjdk.java.net/jeps/427 (preview 3)
    - http://cr.openjdk.java.net/~gbierman/jep427%2b405/jep427+405-20220517/specs/patterns-switch-record-patterns-jls.html
- [ ] Implement "Record Patterns" (405) as a preview feature, mark AST classes as experimental, if needed.
    - https://openjdk.java.net/jeps/405
    - http://cr.openjdk.java.net/~gbierman/jep427%2b405/jep427+405-20220517/specs/patterns-switch-record-patterns-jls.html
- [ ] Remove java language version 17-preview
    - update also java.md and ant.md
    - update KotlinTestingDsl.kt
- [ ] Write release notes
- [ ] Prepare merge for PMD 7 as a new PR
