### ISSUE TITLE
[java] Support JDK 20

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4333]
[OpenJDK 20](https://openjdk.java.net/projects/jdk/20/)  GA is scheduled for 2023/03/21.
So we should add support for that with PMD version 6.55.0 (end of February 2023).

The following JEPs are important for us:
* 432: [Record Patterns (Second Preview)](https://openjdk.org/jeps/432)
* 433: [Pattern Matching for switch (Fourth Preview)](https://openjdk.org/jeps/433)

In summary: https://javaalmanac.io/jdk/20/

This issue is similar to the previous: #4015

EA Release of JDK20 is available here: http://jdk.java.net/20/

**Tasks:**

- [x] Add new java language versions 20 and 20-preview.
    - 20 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
- [x] Update asm dependency to 9.4:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor.ASM_API if necessary
- [x] Remove java language version 18-preview
    - update also java.md and ant.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
- [x] Update implementation for "Pattern Matching for switch" (406, 420, 427, 433) as a preview feature, mark AST classes as experimental, if needed.
    - https://openjdk.org/jeps/406 (preview 1)
    - https://openjdk.org/jeps/420 (preview 2)
    - https://openjdk.org/jeps/427 (preview 3)
    - https://openjdk.org/jeps/433 (preview 4)
      > The main changes since the third preview are:
      > * An exhaustive switch (i.e., a switch expression or a pattern switch statement) over an enum class now throws MatchException rather than IncompatibleClassChangeError if no switch label applies at run time.
      > * The grammar for switch labels is simpler.
      > * Inference of type arguments for generic record patterns is now supported in switch expressions and statements, along with the other constructs that support patterns.

    - http://cr.openjdk.java.net/~gbierman/jep432%2b433/jep432+433-20221115/specs/patterns-switch-record-patterns-jls.html
- [x] Update implementation for "Record Patterns" (405, 432) as a preview feature, mark AST classes as experimental, if needed.
    - https://openjdk.org/jeps/405 (preview 1)
    - https://openjdk.org/jeps/432 (preview 2)
      > The main changes since the first preview are to:
      > * Add support for inference of type arguments of generic record patterns,
      > * Add support for record patterns to appear in the header of an enhanced for statement, and
      > * Remove support for named record patterns.

    - http://cr.openjdk.java.net/~gbierman/jep432%2b433/jep432+433-20221115/specs/patterns-switch-record-patterns-jls.html
- [x] Write release notes
    - removed classes: ASTGuardedPattern
    - deprecated classes: none
    - new experimental: none
- [x] Update https://github.com/pmd/java-regression-tests
    - no new regular language features, so no update needed 
- [x] Prepare merge for PMD 7 as a new PR: #4379
