### ISSUE TITLE
[java] Support JDK 21 (LTS)

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4583]
[OpenJDK 21](https://openjdk.org/projects/jdk/21/)  GA is scheduled for 2023/09/19.

The following JEPs are important for us:
* [JEP 430: String Templates (Preview)](https://openjdk.org/jeps/430)
* [JEP 440: Record Patterns](https://openjdk.org/jeps/440)
* [JEP 441: Pattern Matching for switch](https://openjdk.org/jeps/441)
* [JEP 443: Unnamed Patterns and Variables (Preview)](https://openjdk.org/jeps/443)
* [JEP 445: Unnamed Classes and Instance Main Methods (Preview)](https://openjdk.org/jeps/445)

In summary: https://javaalmanac.io/jdk/21/

This issue is similar to the previous: #4333 

EA Release of JDK21 is available here: https://jdk.java.net/21/

**Tasks:**

- [x] Add new java language versions 21 and 21-preview.
    - 21 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
- [x] Update asm dependency to 9.5:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.symbols.internal.asm.AsmSymbolResolver#ASM_API_V if necessary
- [x] Remove java language version 19-preview
    - update also java.md and ant.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
- [x] Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - add 21/21-preview
    - remove 19-preview
- [x] Update implementation for "Pattern Matching for switch" (406, 420, 427, 433, 441)
    - Promote this feature to a standard language feature (was preview before). E.g. remove experimental
    - https://cr.openjdk.org/~gbierman/jep440%2B441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html
- [x] Update implementation for "Record Patterns" (405, 432, 440)
    - Promote this feature to a standard language feature (was preview before). E.g. remove experimental
    - https://cr.openjdk.org/~gbierman/jep440%2B441/jep440+441-20230612/specs/patterns-switch-record-patterns-jls.html
- [x] Implement preview feature "String Templates" (430)
    - https://cr.openjdk.org/~gbierman/jep430/jep430-20230526/specs/string-templates-jls.html
- [x] Implement preview feature "Unnamed Patterns and Variables" (443)
    - https://cr.openjdk.org/~abimpoudis/unnamed/jep443-20230322/specs/unnamed-jls.html
- [x] Implement preview feature "Unnamed Classes and Instance Main Methods" (445)
    - https://cr.openjdk.org/~gbierman/jep445/jep445-20230524/specs/unnamed-classes-instance-main-methods-jls.html
- [x] Write release notes
    - removed experimental:
        - ASTRecordPattern
        - ASTPatternList (formerly ASTComponentPatternList)
        - ASTGuard (formerly ASTSwitchGuard)
    - removed classes: TODO
    - deprecated classes: TODO
        - net.sourceforge.pmd.lang.java.ast.ASTPattern#getParenthesisDepth - the method is deprecated, because parenthesized patterns are not allowed with Java 21 anymore.
    - new experimental: TODO
      - ASTTemplateExpression
      - ASTTemplate
      - ASTTemplateFragment
      - ASTUnnamedPattern
- [x] Add JDK21 to the build, so that we integration test with 21, as this is a LTS version
    - integration test in pmd-dist
    - ~maybe also build PMD with 21, to avoid issues like #4401~
- Update https://github.com/pmd/java-regression-tests
    - new regular language features, so update needed
    - Note: This can only be done, after this PR has been merged
    - Therefore new issue: #4642

**Comment by Paxa** [comment]
With gradle it can work like this
```gradle
pmd {
    consoleOutput = true
    toolVersion = "7.0.0"
    ruleSetFiles = files("${project.rootDir}/tools/pmd-rules.xml")
    ruleSets = []
}
```
