### ISSUE TITLE
[java] Support JDK 22

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4794]
[OpenJDK 22](https://openjdk.org/projects/jdk/22/)  GA is scheduled for 2024/03/19.

The following JEPs are important for us:
* 447: 	[Statements before super(...) (Preview)](https://openjdk.org/jeps/447)
* 456: 	[Unnamed Variables & Patterns](https://openjdk.org/jeps/456)
* 459: 	[String Templates (Second Preview)](https://openjdk.org/jeps/459)
* 463: 	[Implicitly Declared Classes and Instance Main Methods (Second Preview)](https://openjdk.org/jeps/463)

In summary: https://javaalmanac.io/jdk/22/

This issue is similar to the previous: #4583 

EA Release of JDK22 is available here: https://jdk.java.net/22/

**Tasks:**

- [x] Add new java language versions 22 and 22-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - 22 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Update `net.sourceforge.pmd.lang.java.JavaLanguageModuleTest#previewVersionShouldBeGreaterThanNonPreview`
- [x] Update asm dependency to 9.6:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.symbols.internal.asm.AsmSymbolResolver#ASM_API_V if necessary
- [x] Remove java language version 20-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - update also java.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Remove `net.sourceforge.pmd.lang.java.ast.Java20PreviewTreeDumpTest`  (including resources)
- [x] Update implementation for "String Templates" (430, 459)
    - https://cr.openjdk.org/~gbierman/jep459/jep459-20231114/specs/string-templates-jls.html
    - "Except for a technical change in the types of template expressions, there are no changes relative to the first preview."
- [x] Update implementation for "Implicitly Declared Classes and Instance Main Methods" (445, 463)
    - https://cr.openjdk.org/~gbierman/jep463/jep463-20231030/specs/implicitly-declared-classes-instance-main-methods-jls.html
- [x] Update implementation for "Unnamed Variables & Patterns" (443, 456)
    - https://cr.openjdk.org/~abimpoudis/unnamed/jep456-20231128/specs/unnamed-jls.html
    - Promote this feature to a standard language feature (was preview before). E.g. remove experimental
    - "We here propose to finalize this feature without change."
- [x] Implement preview feature "Statements before super(...)" (447)
    - https://cr.openjdk.org/~gbierman/jep447/jep447-20230927/specs/statements-before-super-jls.html
- [x] Write release notes
    - removed experimental:
      - ASTUnnamedPattern
    - removed classes: -
    - deprecated classes: -
    - new experimental: -
- [x] Add JDK22 to the build, so that we integration test with 22, ~as this is a LTS version~
    - integration test in pmd-dist
    - Not necessary, as JDK22 is not LTS
- [x] Make sure, we can build PMD with JDK22
- [x] Update https://github.com/pmd/java-regression-tests
    - new regular language features, so update needed
    - Note: This can only be done, after this issue has been implemented
    - See https://github.com/pmd/java-regression-tests/pull/2

**Comment by adangel** [comment]
Note: Java 22 includes JEP 457:	[Class-File API (Preview)](https://openjdk.org/jeps/457), which can replace ASM in the future...

**Comment by adangel** [comment]
> Make sure, we can build PMD with JDK22

We can basically build PMD with java 22, but we need to skip pmd/cpd execution. E.g.

`./mvnw clean install -Dpmd.skip=true -Dcpd.skip=true`

I assume, that m-pmd-p doesn't provide the Java Runtime for the auxclasspath and we fall back to load java classfiles from the current runtime, which is Java 22 and we can't read the classfiles (Unsupported class file major version 66). This can be worked around by overriding the asm dependency for m-pmd-p:

```xml
                        <dependency>
                            <groupId>org.ow2.asm</groupId>
                            <artifactId>asm</artifactId>
                            <version>9.6</version>
                        </dependency>
```

However, I didn't add a profile or so, as once PMD 7.0.0 is released, this problem is gone.

In order to make the combination work (Running PMD with Java 22, analyzing source code for Java 8) through maven-pmd-plugin, we probably need to enhance the plugin to provide one more option to explicitly configure the Java Runtime classpath for auxclasspath/type resolution. I'm pretty sure, it would work when configuring Java 8 via toolchains (but then PMD would be executed with Java 8).
