### ISSUE TITLE
[core] TODO list for the properties refactoring

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#504]
The first PR for properties has just been merged (#479). Here's roughly what's left to do, one PR per item:

- [x] **(PR #518)** Work on enumerated properties:
  * Modularise `EnumeratedProperty` and `EnumeratedMultiProperty` like what's been done for eg NumericProperties. That allows both properties to share behaviour even though they're not related inheritance-wise. 
  * Make a new constructor for enumerated properties with the same signature as before (without the `Class<E>` parameter) for retro compatibility, but deprecate it
- [x] **(PR #587)** Move the static constants of `ValueParser` into a new `ValueParsers` class. 
- [x] **(PR #620)** Move all property-related classes and interfaces into `n.s.pmd.properties` (see [this](https://github.com/pmd/pmd/pull/479#pullrequestreview-50103114))
- [x] **(PR #669)** Replace the factories for properties with a Builder pattern (see [this](https://github.com/pmd/pmd/pull/479#pullrequestreview-50103114) and [this](https://github.com/pmd/pmd/pull/479#issuecomment-315488600))
- [x] **(PR #749)** Update/Create documentation about rule properties. See [this](http://pmd.sourceforge.net/snapshot/pmd_devdocs_info_for_developers.html) for the existing docu...
- [x] Update the changelog - document API changes

We also need to complete the documentation and update the tests for good coverage. Feel free to add your ideas!

**Comment by jsotuyod** [comment]
@oowekyala please, update this checklist as PRs are being submitted / merged to help us track progress.

**Comment by adangel** [comment]
@oowekyala I'm going to close this issue - everything is done now and merged into 6.0.0! Great work!

I've updated the changelog to mention the properties changes - but not in great detail: https://github.com/pmd/pmd/blob/master/docs/pages/release_notes.md#rule-and-report-properties

Let me know, if you think, this should be improved.

**Comment by oowekyala** [comment]
@adangel Hurray! I think I just forgot to update the doc page to remove FileProperty and MethodProperty from the XPath section

The release notes are fine, it's probably not worth repeating what's in the doc. But maybe it's worth mentioning that users can declare properties from the XPath though, since it's the first version for which this feature is documented

**Comment by adangel** [comment]
@oowekyala Thanks for the tips! I've updated both doc and release notes.
