### ISSUE TITLE
[java] Support Java 23

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#5062]
Java 23 will be released on September 17th. It ships a number of new feature previews that will impact PMD.

[OpenJDK 23](https://openjdk.org/projects/jdk/23/) GA is scheduled for 2024/09/17.

I here list the JEPs I've so far confirmed to be of impact:

- [467: Markdown Documentation Comments](https://openjdk.org/jeps/467)
  - It allows Javadocs to be written in Markdown using `///` on each line, instead of `/** … */`. This will impact our grammar to identify these as Javadocs, but also all rules parsing these (ie: to detect unused imports).
- [476: Module Import Declarations (Preview)](https://openjdk.org/jeps/476)
  - Preview feature, allows modules to be imported directly, treating all public classes in exported packages to be imported on demand. This will affect the grammar around imports, affect all rules working with them, and may require us to revamp how PMD models and manages modules (which is quite weak honestly, as no rules currently deal with them directly).
- [482: Flexible Constructor Bodies (Second Preview)](https://openjdk.org/jeps/482)
  - Not much changed since the first preview at first glance, need to double check…
- [455: Primitive Types in Patterns, instanceof, and switch (Preview)](https://openjdk.org/jeps/455)
  - Relaxed constraints on what is allowed in these patterns. Should be easy, but needs appropriate tests to be added.
- [477: Implicitly Declared Classes and Instance Main Methods (Third Preview)](https://openjdk.org/jeps/477)

In summary: https://javaalmanac.io/jdk/23/

This issue is similar to the previous: #4794

EA Release of JDK23 is available here: https://jdk.java.net/23/

**Tasks:**

- [x] Add new java language versions 23 and 23-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - 23 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Update `net.sourceforge.pmd.lang.java.JavaLanguageModuleTest#previewVersionShouldBeGreaterThanNonPreview`
    - Update `net.sourceforge.pmd.lang.java.ast.AllJavaAstTreeDumpTest`
    - Update `net.sourceforge.pmd.dist.BinaryDistributionIT`
- [x] Update asm dependency to 9.7:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.symbols.internal.asm.AsmSymbolResolver#ASM_API_V if necessary
- [x] Remove java language version 21-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - update also java.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Remove `net.sourceforge.pmd.lang.java.ast.Java21PreviewTreeDumpTest`  (including resources)
- [x] Update implementation for "Implicitly Declared Classes and Instance Main Methods" (445, 463, 477)
    - https://cr.openjdk.org/~gbierman/jep477/jep477-20240507/specs/implicitly-declared-classes-instance-main-methods-jls.html
- [x] Update implementation for "Flexible Constructor Bodies" (447, 482)
    - JEP was named before "Statements before super(...)"
    - https://cr.openjdk.org/~gbierman/jep482/jep482-20240604/specs/flexible-constructor-bodies-jls.html
- [x] Implement preview feature "Markdown Documentation Comments" (467)
- [x] Implement preview feature "Module Import Declarations" (476)
    - https://cr.openjdk.org/~gbierman/jep476/jep476-20240604/specs/module-import-declarations-jls.html
- [x] Implement preview feature "Primitive Types in Patterns, instanceof, and switch" (455)
    - https://cr.openjdk.org/~abimpoudis/instanceof/jep455-20240424/specs/instanceof-jls.html
- [x] Remove support for String Templates (430, 459)
    - It was decided, that String Templates will be removed: See https://bugs.openjdk.org/browse/JDK-8329949 and https://www.youtube.com/watch?v=c6L4Ef9owuQ
    - It should only work with 22-preview, but not anymore with 23-preview
    - It might come back in some way, but if it doesn't come back for 24, we can remove the code completely from our grammar.
- [x] Write release notes
    - removed experimental: done
    - removed classes: none
    - deprecated classes: none
    - new experimental: done
- [x] Add JDK23 to the build, so that we integration test with 23, ~as this is a LTS version~
    - integration test in pmd-dist
    - Not necessary, as JDK23 is not LTS
- [x] Make sure, we can build PMD with JDK23
- [x] Update https://github.com/pmd/java-regression-tests
    - ~new regular language features, so update needed~
    - not necessary for 23, as there are no new regular language features
    - Note: This can only be done, after this issue has been implemented
- [x] Create a new issue for the next Java version 24
    - https://jdk.java.net/24/
    - https://openjdk.org/projects/jdk/24/
    - #5154
