### ISSUE TITLE
[java] Support Java 24

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#5154]
Java 24 will be released in March 2025.

[OpenJDK 24](https://openjdk.org/projects/jdk/24/) GA is scheduled for 2025/03/18.

I here list the JEPs I've so far confirmed to be of impact:

- 488: 	[Primitive Types in Patterns, instanceof, and switch (Second Preview)](https://openjdk.org/jeps/488)
- 494: 	[Module Import Declarations (Second Preview)](https://openjdk.org/jeps/494)
- 495: 	[Simple Source Files and Instance Main Methods (Fourth Preview)](https://openjdk.org/jeps/495)
- 492: 	[Flexible Constructor Bodies (Third Preview)](https://openjdk.org/jeps/492)

In summary: https://javaalmanac.io/jdk/24/

This issue is similar to the previous: #5062

EA Release of JDK24 is available here: https://jdk.java.net/24/

**Tasks:**

- [x] Add new java language versions 24 and 24-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - 24 is the new default
    - update also java.md and ant.md
    - and add in KotlinTestingDsl.kt.
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Update `net.sourceforge.pmd.lang.java.JavaLanguageModuleTest#previewVersionShouldBeGreaterThanNonPreview`
    - Update `net.sourceforge.pmd.lang.java.ast.AllJavaAstTreeDumpTest`
    - Update `net.sourceforge.pmd.dist.BinaryDistributionIT`
- [x] Update asm dependency to 9.8 ??:
    - https://search.maven.org/artifact/org.ow2.asm/asm
    - https://asm.ow2.io/versions.html
    - Update net.sourceforge.pmd.lang.java.symbols.internal.asm.AsmSymbolResolver#ASM_API_V if necessary
    - Maybe already done by #5288
    - 2025-01-18 - asm 9.7.1 is still the latest version, so nothing to do here.
- [x] Remove java language version 22-preview: `net.sourceforge.pmd.lang.java.JavaLanguageModule`
    - update also java.md
    - update KotlinTestingDsl.kt
    - remove exclusions in pmd-core/src/main/resources/internal/all-java.xml
    - Update `net.sourceforge.pmd.lang.java.LanguageVersionTest`
    - Remove `net.sourceforge.pmd.lang.java.ast.Java22PreviewTreeDumpTest`  (including resources)
    - Update `net.sourceforge.pmd.lang.java.ast.AllJavaAstTreeDumpTest`
    - Update `net.sourceforge.pmd.dist.BinaryDistributionIT`
- [x] Update implementation for [JEP 455: Primitive Types in Patterns, instanceof, and switch (Preview)](https://openjdk.org/jeps/455)
    - New JEP: [JEP 488: Primitive Types in Patterns, instanceof, and switch (Second Preview)](https://openjdk.org/jeps/488)
    - "We here propose to preview it for a second time, without change."
    - https://cr.openjdk.org/~abimpoudis/instanceof/jep488-20241029/specs/primitive-types-in-patterns-instanceof-switch-jls.html
- [x] Update implementation for [JEP 482: Flexible Constructor Bodies (Second Preview)](https://openjdk.org/jeps/482)
    - New JEP: [JEP 492: Flexible Constructor Bodies (Third Preview)](https://openjdk.org/jeps/492)
    - "We here propose to preview it for a third time, without significant change."
    - https://cr.openjdk.org/~gbierman/jep492/jep492-20241205/specs/flexible-constructor-bodies-jls.html
- [x] Update implementation for [JEP 476: Module Import Declarations (Preview)](https://openjdk.org/jeps/476)
    - New JEP: [JEP 494: Module Import Declarations (Second Preview)](https://openjdk.org/jeps/494)
    - "We here propose to preview them for a second time to gain more experience and feedback, with two additions:

      * Lift the restriction that no module is able to declare a transitive dependence on the java.base module, and revise the declaration of the java.se module to transitively require the java.base module. With these changes, importing the java.se module will import the entire Java SE API on demand.

      * Allow type-import"
    - https://cr.openjdk.org/~gbierman/jep494/jep494-20241024/specs/module-import-declarations-jls.html
- [x] Update implementation for [JEP 477: Implicitly Declared Classes and Instance Main Methods (Third Preview)](https://openjdk.org/jeps/477)
    - New JEP: [JEP 495: Simple Source Files and Instance Main Methods (Fourth Preview)](https://openjdk.org/jeps/495)
    - "We here propose to preview it for a fourth time, with new terminology and a revised title but otherwise unchanged, in order to gain additional experience and feedback."
    - https://cr.openjdk.org/~gbierman/jep495/jep495-20241101/specs/simple-source-files-instance-main-methods-jls.html
- [x] Remove implementation of String Templates
    - 22-preview was the last version that supported that
- [x] Write release notes
    - removed experimental: TODO
    - removed classes: TODO
    - deprecated classes: TODO
    - new experimental: TODO
- [x] Add JDK24 to the build, so that we integration test with 24, ~as this is a LTS version~
    - integration test in pmd-dist
    - Not necessary, as JDK24 is not LTS
- [x] Make sure, we can build PMD with JDK24
- [x] Update https://github.com/pmd/java-regression-tests
    - ~new regular language features, so update needed~ not necessary, as no new standard language features
    - Note: This can only be done, after this issue has been implemented
- [x] Create a new issue for the next Java version 25
    - https://jdk.java.net/25/
    - https://openjdk.org/projects/jdk/25/
    - See #5478
