### ISSUE TITLE
[all] Breaking API changes for 7.0.0

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#881]
List of breaking API changes and deprecated APIs to be removed for 7.0.0:
- [x] Make AbstractJspNode, AbstractVFNode, and AbstractLombokAwareRule abstract classes
- [x] Remove default implementation of getXPathNodeName from AbstractNode
- [x] The toString methods of nodes can be repurposed as soon as 7.0.0 to output more useful debugging info, see #879  
- [x] Move `JavaQualifiedName` out of the `net.sourceforge.pmd.lang.java.ast`, as it's not part of the AST in any way.
- [x] Add method `getFormalParameters()` in interface `ASTMethodOrConstructorDeclaration`
- [x] change return type of `Object getNextToken();` in `n.s.p.lang.TokenManager` to `GenericToken` or even `T` (with `<T extends GenericToken>`). See #1039 

Deprecated APIs:
- [x] `AbstractNode.hasDecendantOfAnyType`
- [x] `n.s.pmd.util.viewer.gui` (old ast viewer)
- [x] `n.s.pmd.util.designer` (old designer)
- [x] `PMD.VERSION`
    - deprecated on master
    - removed in pmd/7.0.x via https://github.com/pmd/pmd/commit/9d1c1860cb630a713aad0055411a2ae084033039
- [x] `RuleSetFactory(ClassLoader, RulePriority, boolean, boolean)`
    - deprecated on master
    - removed in pmd/7.0.x via https://github.com/pmd/pmd/commit/94028a1ce6289ea794f109308eef672f072215c5 and #2969
- [x] Previous rule dependency accessors:
  - [x] `Rule.usesDFA`, `Rule.usesTypeResolution`, `Rule.usesMultifile`, `Rule.usesRuleChain`
  - [x] `Rule.setUsesDFA`, `Rule.setUsesTypeResolution`, `Rule.setUsesMultifile`
  - [x] Implementations in `AbstractRule` and `AbstractDelegateRule`
- [x] Old benchmark API, in `n.s.pmd.benchmark`:
  - [x] Benchmark
  - [x] Benchmarker
  - [x] BenchmarkReport
  - [x] BenchmarkResult
  - [x] RuleDuration
  - [x] StringBuilderCR
  - [x] TextReport
- [x] `StringUtil` members:
  - [x] `startsWithAny`
  - [x] `isNotEmpty`
  - [x] `isEmpty`
  - [x] `isMissing`
  - [x] `areSemanticEquals`
  - [x] `replaceString` (2 overloads)
  - [x] `substringsOf`(2 overloads)
  - [x] `asStringOn` (2 overloads)
  - [x] `lpad`
- [x] `CollectionUtil` members (IIRC some of these implementations should be moved to the eclipse plugin)
  - [x] `arraysAreEqual`
  - [x] `valuesAreTransitivelyEqual`
  - [x] `areEqual`
  - [x] `areSemanticEquals`
  - [x] `addWithoutDuplicates` (2 overloads)
- [x] Property constructors (it may make sense to deprecate some other ones too)
  - [x] `EnumeratedProperty<E>(String, String, String[], E[], int, float)`
  - [x] `EnumeratedProperty<E>(String, String, String[], E[], int, Class<E>, float)`
- [x] `PMDParameters. transformParametersIntoConfiguration `
- [x] `net.sourceforge.pmd.pmd.dcd.graph.MemberNode.equals(...)`
- [x] `ASTConstructorDeclaration.getParameters()`
- [x] deprecate `Node`'s `<T> void findDescendantsOfType(Class<T> targetType, List<T> results, boolean crossFindBoundaries)`
- [x] deprecate `Node`'s `<T> void findDescendantsOfType(Class<T> targetType, List<T> results, boolean crossFindBoundaries)`
- [x] add `public <T> List<T> findDescendantsOfType(final Class<T> targetType, final boolean crossBoundaries)` to `Node`
- [x] Remove class `net.sourceforge.pmd.util.log.ConsoleLogHandler` entirely (see #1045)
  - deprecated on master
  - removed on pmd/7.0.x with https://github.com/pmd/pmd/commit/bc6806d0f16792d41b88801cb80353eb7e386ee0 and #3789
- [x] Make `net.sourceforge.pmd.lang.java.ast.ASTFormalParameter::setVarargs()` package-private
  * Actually *every* `setXX` method of AST nodes that's only used by the parser should be made package private
- [x] Remove class `net.sourceforge.pmd.lang.java.xpath.TypeOfFunction` entirely
- [x] Remove all overloads of `typeof` from `net.sourceforge.pmd.lang.java.xpath.JavaFunctions`
- [x] Remove `isA`, `isEither` and `isNeither` from `net.sourceforge.pmd.lang.java.typeresolution.TypeHelper`
- [x] Remove `CommentUtil` (see #1198, #2802)
- [x] Remove `AbstractCommentRule.tagsIndicesIn()` (see #1198, #2802)
- [x] `ASTImportDeclaration` should no longer be a `TypeNode`
- [x] `ASTImportDeclaration`'s `setImportOnDemand` and  `setStatic` should be made package-private
- [x] Remove `ASTConditionalExpression.setTernary` and `ASTConditionalExpression.isTernary`
- [x] Remove package `net.sourceforge.pmd.lang.dfa.report` (see #1283)
- [x] Remove deprecated apex visit(ApexNode<?>...) (see #1408)

**Open**
- [x] Remove class `net.sourceforge.pmd.cli.PMDParameters.RulePriorityConverter` entirely (see #1147)
  - deprecated on master
- [x] `RuleSetWriter.RULESET_NS_URI`
    - deprecated on master
- [x] `net.sourceforge.pmd.lang.rule.RuleReference.RuleReference()` (default constructor)
   - deprecated on master
- [x] Remove `pmd-core/src/main/resources/net/sourceforge/pmd/util/viewer/resources/viewer_strings.properties`
   - it was used be the old ui viewer, which was removed with #1431 already

**Remaining tasks:**
- Deprecated methods around (Abstract)PropertySource (see #1322)
  - moved to #4301
