### ISSUE TITLE
[java] Improve naming conventions rules

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#972]
I thought about my former gitter comments and would like to begin working on it. This is an implementation plan, but of course anyone should feel free to chime in

The goal is to make the naming conventions rules much more granular and configurable. Our current rules are 
* [MethodNamingConventions](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#methodnamingconventions), which isn't configurable at all
* [ClassNamingConventions](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#classnamingconventions), same thing
* [GenericsNaming](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#genericsnaming), same thing
* [VariableNamingConventions](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#variablenamingconventions), which uses a weird mix of properties which are confusing and have limited practical use 

I'm proposing to change these in the following way (probably one PR per item):

- [x] **(PR #975)** Create a RegexProperty property type...
- [x] **(PR #1007)** ... and use it to make ClassNamingConventions... 
- [x] **(PR #1040)** ... and MethodNamingConventions configurable. The goal is to be able to configure a different pattern for enum, annotation, abstract classes, static methods, etc
- [x] **(PR #1214)** Split VariableNamingConventions into three new rules: LocalVariableNamingConventions, FormalParameterNamingConventions, ...
- [x] **(PR #1296)**... and FieldNamingConventions. For each of those, use regex properties to customise patterns for eg constants (public static final fields), final fields, enum constants, lambda parameters, etc. 
- [ ] #5922
  - Rename GenericsNaming to TypeParameterNamingConventions and provide configurability as well

#### Rule deprecation

The following rules become special cases of the more general new rules

- [x] [AbstractNaming](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#misleadingvariablename) -> superseded by ClassNamingConventions
- [x] [MIsLeadingVariableName](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#misleadingvariablename) -> superseded by LocalVariableNamingConventions and MethodParameterNamingConventions
- [x] [AvoidPrefixingMethodParameters](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#avoidprefixingmethodparameters) -> superseded by MethodParameterNamingConventions
- [x] [SuspiciousConstantFieldName](https://pmd.github.io/pmd-6.1.0/pmd_rules_java_codestyle.html#suspiciousconstantfieldname) -> this one looks backwards to me, and is superseded by FieldNamingConventions anyway 

Possibly also
- ShortVariable and LongVariable
  - see #5950
- ShortMethodName
  - see #5952
- ShortClassName
  - see #5951

**Comment by jsotuyod** [comment]
I believe we should address #953 as part of the `VariableNamingConventions` refactor
